/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Test_routeRouteImport } from './routes/test_route'
import { Route as IndexRouteImport } from './routes/index'

const Test_routeRoute = Test_routeRouteImport.update({
  id: '/test_route',
  path: '/test_route',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test_route': typeof Test_routeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test_route': typeof Test_routeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test_route': typeof Test_routeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test_route'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test_route'
  id: '__root__' | '/' | '/test_route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Test_routeRoute: typeof Test_routeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test_route': {
      id: '/test_route'
      path: '/test_route'
      fullPath: '/test_route'
      preLoaderRoute: typeof Test_routeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Test_routeRoute: Test_routeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
